ALTER TABLE topics
  ADD COLUMN IF NOT EXISTS access_level VARCHAR(50) NOT NULL DEFAULT 'members',
  ADD COLUMN IF NOT EXISTS visibility VARCHAR(50) NOT NULL DEFAULT 'visible',
  ADD COLUMN IF NOT EXISTS notifications_muted BOOLEAN NOT NULL DEFAULT FALSE;
